### ISSUE TITLE
Feedback for the SRS

### ISSUE THREAD

**Issue by doinoob** [mac-casellaj/LiDart#13]
In functional requirements and non-functional requirements, the requirements are state general and complete, however, you missed the rationales for each requirement. Rationales are necessary to put because they can tell the readers why a requirement is needed. Additionally, you are suggested to have fit criterias for each requirement, which can provide metrics to evaluate and test the requirements.

**Comment by KareemElmokattaf** [comment]
This has been confirmed and changed
