### ISSUE TITLE
SRS-Review-Team8-Junhong Chen

### ISSUE THREAD

**Issue by JunhongC-coder** [mac-casellaj/LiDart#14]
In the Requirements Dependencies section of SRS, you provide a table to show traceability. However, the table doesn't include all the requirements that you mention in sections 5.1 and 5.2. This may lead to ambiguity and confusion because readers have no idea whether the remaining requirements you leave out have dependency relationships to other requirements or not. It would be much better to write a statement to mention that the requirements that are not in the table have no dependency on other requirements if the table does not include all the requirements.

**Comment by KareemElmokattaf** [comment]
This has been confirmed and changed
