### ISSUE TITLE
SRS Review -- Tingyu Shi

### ISSUE THREAD

**Issue by tingyushi** [mac-casellaj/LiDart#16]
Hello, All members of team 10,

The first functional requirement is not abstract enough. Using a keyboard or a mouse are implementation decisions. I think it is enough to just say "The system shall be able to take user inputs".
Maybe it's better to have fit criterion for each non-functional requirement, this will be helpful when it comes to testing.
For the development plan, it would be better to see what specific requirements will be completed in what phase. For example, you can say "Requirements 1-5 will be completed in phase 1".
Overall, this is a great SRS.

Thanks,
Tingyu Shi
@samm82

**Comment by KareemElmokattaf** [comment]
@michaela-schnull
This has been changed and confirmed
