### ISSUE TITLE
Team8_HazardAnalysis_Review_Tingyu_Shi

### ISSUE THREAD

**Issue by tingyushi** [mac-casellaj/LiDart#22]
I like the two figures included in your System Processes part. They can give readers a clear overview of the workflow of your system. 
For H 2-2, I think more details could be better. You can elaborate on how the robot may crash in different ways.

Thanks,
Tingyu Shi
@samm82

**Comment by KareemElmokattaf** [comment]
Other methods that the robot can crash are included in the table, we avoided adding it to the H2-2 row due to redundancy.
