### ISSUE TITLE
Team6 Review - Vnv

### ISSUE THREAD

**Issue by michaelilao** [mac-casellaj/LiDart#25]
Great report and very detailed! For 4.6.4 EAGLE testing or design tool was said to be used. More information should be provided on what this tool is and what its capabilities are as for someone whos never used this tool before is unsure what it does and how it can benefit your project and its use is?

**Comment by KareemElmokattaf** [comment]
The document talks about how EAGLE has built-in error checking tools which are very helpful to have. The tools are then specified (ERC and DRC).
