### ISSUE TITLE
Team 6 VnV Plan Review

### ISSUE THREAD

**Issue by Hargun22** [mac-casellaj/LiDart#26]
Overall, great work! One thing I noticed is that for T11, it is mentioned that the robot should have a low charge; It is unclear what value(s) would be considered "low" charge. It would've been less ambiguous if an actual number was provided like 20% or 10%.  

@CSchank

**Comment by KareemElmokattaf** [comment]
[https://github.com/mac-casellaj/LiDart/commit/38ba320ca12a5e7b78e73f8e448c8f28cbfe90e2](https://github.com/mac-casellaj/LiDart/issues/url)
Adds information as suggested in this feedback
