### ISSUE TITLE
Team 6 VnV Plan Review 

### ISSUE THREAD

**Issue by Martin-Mai** [mac-casellaj/LiDart#27]
Hi, it is a great VnV report plan. For T11 in Tests for Functional Requirements R8. Could you please provide more information about what tools that you are going to charge your robot?

**Comment by KareemElmokattaf** [comment]
[https://github.com/mac-casellaj/LiDart/commit/38ba320ca12a5e7b78e73f8e448c8f28cbfe90e2](https://github.com/mac-casellaj/LiDart/issues/url)
Adds information as suggested in this feedback
