### ISSUE TITLE
Team 6 VnV Plan Review

### ISSUE THREAD

**Issue by Dorps** [mac-casellaj/LiDart#28]
Good work on your VnV plan! I like the coverage of the test plan and how it discusses both the physical components and software aspects of your system. A piece of feedback for better clarity of your VnV project is I would describe whether or not a test is automated or not for your software components as there may be some tests where you would not want to consistently always test manually as you build your project.

@CSchank

**Comment by KareemElmokattaf** [comment]
Issue Closed
