### ISSUE TITLE
Team 6 V&V Review

### ISSUE THREAD

**Issue by EngandDeveloper** [mac-casellaj/LiDart#29]
Great V&V plan. I think it had pretty good detail. Your scope and introduction sections explained the purpose of the document very clearly. I have a small suggestion that may help with test cases. Since the detail level of test cases should be enough for an outsider to perform the test with the information provided on this document, I think the initial states of the test cases can be a little bit more detailed to make sure the tester can reproduce the correct test cases and get the expected outputs. For example in T1, you gave the initial state as GUI to be open but it doesn't say anything about the initial state of the robot. Is the robot stationary or is it already moving to a direction? I think if you include the necessary details, your V&V Plan documentation will be complete.

@CSchank

**Comment by KareemElmokattaf** [comment]
[https://github.com/mac-casellaj/LiDart/commit/38ba320ca12a5e7b78e73f8e448c8f28cbfe90e2](url)
Adds information as suggested in this feedback
