### ISSUE TITLE
Team 4 - VnV Report Review - Expand Reflection

### ISSUE THREAD

**Issue by aujlaa4** [mac-casellaj/LiDart#41]
Great job on the VnV report! The majority of your test results go into great detail and the report is easy to follow.

In the Changes Due to Testing section, you stated that users reported that they would prefer to use a controller rather than a keyboard and mouse to control the robot. This is a good observation, although you could expand on how you could have found this out before this stage of the project. Would it have been beneficial to ask potential users this in the planning stage of the project? Reflections such as this would further show that you have learned from the VnV process.

**Comment by KareemElmokattaf** [comment]
Issue closed
