### ISSUE TITLE
Team 4 VnV Report Review: Only One Nonfunctional Quality Dataset Present

### ISSUE THREAD

**Issue by vankraa** [mac-casellaj/LiDart#42]
Report is well done and easy to follow. The traceability to the VnV Plan is clear and organized. There seems to be only one set of data that verifies a Nonfunctional requirement when there should be two. Analyzing another aspect of the project would add more code validation and ensure a greater robustness to the project.

**Comment by KareemElmokattaf** [comment]
Issue closed
