### ISSUE TITLE
Team 4 VNV Report Review: Changes Due to Testing next steps

### ISSUE THREAD

**Issue by jtgc1** [mac-casellaj/LiDart#44]
This is a super interesting project, nice to read about MvM's course in with context :). The one thing I would have liked to see in this document was some more detail in the Changes Due to Testing section regarding future design changes. 
For example, when discussing NFR1 (3D scan accuracy), you mention some potential sources for failing the test. However, there is only a brief mention of "improved versions", but no mention of what those changes are. Some more detail for each of the parts of this section would be nice.

**Comment by KareemElmokattaf** [comment]
Issue closed
