### ISSUE TITLE
Team 4 - VnV Report Review - Testing Failure Handling

### ISSUE THREAD

**Issue by celsj** [mac-casellaj/LiDart#45]
I see test T14.4 and T14.5 that test the fault state of the robot, but otherwise I do not see any tests for when things go wrong. I would like to see more testing around what happens when certain parts fail. For example, what is the error handling for if the WIFI connection were to be severed partway through use? Or if connection to the GUI was broken partway through?

**Comment by KareemElmokattaf** [comment]
Issue Closed
